version: '3.7'
services:
  monolito:
    container_name: monolito
    image: monolito:v1
    build:
      context: .
    ports:
      - "4001:4001"
    networks:
      - app-network

networks:
  app-network: